### ISSUE TITLE
助记词功能异常

### ISSUE THREAD

**Issue by MonveChen** [starcoinorg/starmask-extension#1]
通过助记词得到的账户地址0xfeBD4cB2A1b5B56F75D2207040544fb950e698C6和通过私钥得到的账户地址不一致，甚至长度都不一致

**Comment by wk3368** [comment]
fixed in https://github.com/starcoinorg/starmask-extension/commit/db6f6097c3fd0e58a12c3502299fdf0f9b44c3e3
chrome extension package 0.6.0 is submitted to chrome  web store, will be published after it passed the review.
