### ISSUE TITLE
starcoin插件钱包会与小狐狸metamask产生冲突

### ISSUE THREAD

**Issue by ggdi** [starcoinorg/starmask-extension#3]
在chrome浏览器的下，如果同时安装了meta mask和star mask，项目网站在调用钱包时会网站前端会假死。个人怀疑是因为前端网站不能识别meta mask 与 star mask之间的区别。所以导致网站假死。

**Comment by wk3368** [comment]
fixed with https://github.com/starcoinorg/starmask-extension/commit/53c8f335c7ef63381beeb0cc35afbf4e9ba0797b

package 0.5.1 has been submitted for review in the chrome web store, should be published soon.
