### ISSUE TITLE
提供 AutoAcceptToken 的开关设置

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starmask-extension#34]
在 stdlibv6 之后创建的用户默认打开了 AutoAcceptToken，但之前的老用户需要手动打开一下这个开关。
现在第三方应用引导用户时需要考虑到老用户，让用户接受 Token 比较复杂，如果有了这个开关就直接建议打开这个开关。

希望 starmask 提供一个设置项目，用户可以直观的看到这个开关，并进行操作。

1. 判断是否打开的方法，获取账号下的 resource 0x1::Account::AutoAcceptToken， 如果该 resource 不存在，或者 AutoAcceptToken 的 enable 字段为 false，则认为该账号未打开这个开关。

```
state get resource 0xxxxxx 0x1::Account::AutoAcceptToken
{
  "ok": {
    "raw": "0x01",
    "json": {
      "enable": true
    }
  }
}
```

2. 打开和关闭开关的方法
```
打开：0x1::AccountScripts::enable_auto_accept_token
关闭：0x1::AccountScripts::disable_auto_accept_token

这两个方法都没有参数
```

**Comment by wk3368** [comment]
添加的这个开关，默认值是打开？

**Comment by wk3368** [comment]
add demo in starmask-test-dapp

![image](https://user-images.githubusercontent.com/171268/142829762-a40c85bd-261c-4a76-8c17-0eda80c8e800.png)

**Comment by wk3368** [comment]
add switch in starmask->settings->advanced:

![image](https://user-images.githubusercontent.com/171268/142830526-9d5db8fe-5a89-4148-8f3c-86e6d45008d3.png)

**Comment by jolestar** [comment]
> add switch in starmask->settings->advanced:
> 
> ![image](https://user-images.githubusercontent.com/171268/142830526-9d5db8fe-5a89-4148-8f3c-86e6d45008d3.png)

这个描述感觉有问题，这个开关控制的是链上的 AutoAcceptToken 还是钱包的一个开关？当添加自定义代币的时候同时自动接受该代币？我看描述的感觉是后者。

但如果是后者，感觉没必要加开关，因为添加代币，但不接受，这种情况没有意义，用户也接受不了别人转账。

如果是前者，需要用户发起交易打开开关，并且每个地址不一样，也不能放在钱包的全局设置里。

**Comment by wk3368** [comment]
当然是前者，我把这个开关挪到帐户的详情页面里去吧。

**Comment by wk3368** [comment]
![image](https://user-images.githubusercontent.com/171268/142977291-97ec1551-3e84-4828-b5cc-4cd205fe0aa8.png)

![image](https://user-images.githubusercontent.com/171268/142977317-37044449-6a1c-4477-8b41-a2decdea74b4.png)

**Comment by jolestar** [comment]
感觉描述应该改成：

选中该项可以在收到新种类的代币转账的同时自动接受该代币，否则必须先手动接受该代币

**Comment by wk3368** [comment]
再加三个字： 添加并
选中该项可以在收到新种类的代币转账的同时自动接受该代币，否则必须先手动添加并接受该代币

**Comment by wk3368** [comment]
![image](https://user-images.githubusercontent.com/171268/143175746-d9278844-553a-4e1a-9b7b-5064e7d350d3.png)

![image](https://user-images.githubusercontent.com/171268/143175781-9aa8fdc3-4cbe-422e-b749-0635e06d6e39.png)

**Comment by wk3368** [comment]
added in v3.1.0

**Comment by Foorgoo** [comment]
个人建议还是别要“新种类”了，也尽量避免“接受”这个概念。
建议改为：选中该项可以自动接收代币转账，否则必须先手动添加代币并接受方可接收转账。
