### ISSUE TITLE
StarMask: Received invalid network parameters.

### ISSUE THREAD

**Issue by tw7613781** [starcoinorg/starmask-extension#4]
In chrome dev tool, the follow error keep showing
StarMask version: 0.5.1
Chrome version: Version 90.0.4430.212 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/4134193/118422017-4d9c4480-b6fd-11eb-87e3-1665f110f7dc.png)

**Comment by wk3368** [comment]
fixed in 0.6.0.
starmask-extension package 0.6.0 is submitted to the chrome web store, it will be published after it passed the review.
