### ISSUE TITLE
Starmask钱包Import Token时出现的错误

### ISSUE THREAD

**Issue by fuhongxuelook** [starcoinorg/starmask-extension#40]
地址在钱包中默认展示为大小写混合的形式,如 : 0x0A7B8DAb322448AF454FccAfFBCbF247
一般import token时候, 按照address::Module::Struct模型

那么
按照address大小写混合形式，如0x0A7B8DAb322448AF454FccAfFBCbF247::TokenA::TokenA, 则无法展示Token数量；

如果address纯小写形式,如0x0a7b8dab322448af454fccaffbcbf247::TokenA::TokenA,则可以正确展示token数量；

推测原因：在请求链上数据时, TypeArgs传入大小写混合地址，链上无法识别。

**Comment by wk3368** [comment]
在barnard上 添加大小写混合的 0x07fa08a855753f0Ff7292fdCbE871216::Bot::Bot，成功
![image](https://user-images.githubusercontent.com/171268/149286371-90fecac3-6570-49c4-9ed4-4ebccca0d431.png)

![image](https://user-images.githubusercontent.com/171268/149286418-4671c3f6-0098-4618-b913-cf4076d4033b.png)

此bug不可重现， close！

**Comment by wk3368** [comment]
![image](https://user-images.githubusercontent.com/171268/149296665-23dfdc41-0e28-4a14-b0ea-fa7d463b7e31.png)

state.list_resources 返回点code的address是全小写的

如果add token的时候，address是大小写混合，会在生成 tokensWithBalances 的时候，没法匹配，导致余额为0

**Comment by wk3368** [comment]
fixed in v3.4.0
