### ISSUE TITLE
Transactions stuck in the starmask queue

### ISSUE THREAD

**Issue by jolestar** [starcoinorg/starmask-extension#44]
### Workaround method to fix:

1. backup starmask and reinstall the starmask, and import account.

**Comment by wk3368** [comment]
![2022-01-04 14 03 15](https://user-images.githubusercontent.com/171268/148016214-d27af1d2-e35b-4c1e-a071-c47eb9ea7ac1.jpg)

sequence number is empty

**Comment by wk3368** [comment]
one solution：
close chrome，and reopen， all transactions that state is APPROVED will be reseted to FAIL on boot up
![image](https://user-images.githubusercontent.com/171268/148084716-a1c0b856-2d03-454c-9965-776c29838214.png)
