### ISSUE TITLE
添加 starswap lp 代币时报错，提示无效合约代码

### ISSUE THREAD

**Issue by liuxieric123** [starcoinorg/starmask-extension#48]
![image](https://user-images.githubusercontent.com/13506627/150631516-f6d78dc1-d370-4eff-9260-1131b24bd031.png)

在 StarMask 中添加 starswap 的 lp 代币时报错

0x4783d08fb16990bd35d83f3e23bf93b8::TokenSwap::LiquidityToken<0x00000000000000000000000000000001::STC::STC,0x4783d08fb16990bd35d83f3e23bf93b8::STAR::STAR>
可以在 barnard 上尝试一下代币复现错误

**Comment by wk3368** [comment]
starmask里面不支持添加这种带 <> 的token

**Comment by wk3368** [comment]
你看一下 这个文本输入框上面提示的代币合约代码的格式

**Comment by wk3368** [comment]
fixed in v3.6.1
