### ISSUE TITLE
The account name will be reset every time log in

### ISSUE THREAD

**Issue by geometryolife** [starcoinorg/starmask-extension#62]
After trying to log in multiple times, the account name will be reset to Account[number] every time. 
Is it possible to set it to not reset?

**Comment by jolestar** [comment]
How to reproduce this bug? can you record a video for this?

**Comment by geometryolife** [comment]
> How to reproduce this bug? can you record a video for this?

![d](https://user-images.githubusercontent.com/54882546/166447847-ec004cb6-866e-4c99-b298-50d88af6be00.gif)

**Comment by geometryolife** [comment]
> How to reproduce this bug? can you record a video for this?

I did a test, I set the three account names in the wallet as Tom, Bob and Alice, and then reset to Account1, Account2 and Account3 after logging in again.

**Comment by jolestar** [comment]
> > How to reproduce this bug? can you record a video for this?
> 
> I did a test, I set the three account names in the wallet as Tom, Bob and Alice, and then reset to Account1, Account2 and Account3 after logging in again.

The name is saved to extension local storage if you remove the extension, will be lost the name, but the address is kept. This is not a bug.

**Comment by geometryolife** [comment]
> > > How to reproduce this bug? can you record a video for this?
> > 
> > 
> > I did a test, I set the three account names in the wallet as Tom, Bob and Alice, and then reset to Account1, Account2 and Account3 after logging in again.
> 
> The name is saved to extension local storage if you remove the extension, will be lost the name, but the address is kept. This is not a bug.

Okay, I got it.
