### ISSUE TITLE
[new feature] 增加对 IdentifierNFT的显示功能

### ISSUE THREAD

**Issue by WGB5445** [starcoinorg/starmask-extension#78]
希望可以支持在 钱包中显示 IdentifierNFT

**Comment by jolestar** [comment]
> 希望可以支持在 钱包中显示 IdentifierNFT

不已经支持了吗？

**Comment by WGB5445** [comment]
> > 希望可以支持在 钱包中显示 IdentifierNFT
> 
> 不已经支持了吗？

我这里没有显示出来，从资源浏览器中可以查到，Chrome 和 Edge 都更新为最新版，但是仍然没有显示

**Comment by wk3368** [comment]
Supported in v4.7.0

**Comment by wk3368** [comment]
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/171268/184062911-d1e557f6-3af2-441c-b6a6-053f0f47e90b.png">

**Comment by wk3368** [comment]
支持下面两种类型的图片：
1. base64
image_data: "data:image/png;base64..."

2. url（http/https/ipfs)
image: "ipfs://QmSifFzarzzen5Vv4TWWhpN56VksqZrF3Bmuuc4gdGTEv1/5669.png"
image: "https://xxxx.png"
image: "http://xxxx.png"

**Comment by jolestar** [comment]
@geometryolife 这个也需要在 cookbook 中说明一下， NFT 的章节
