### ISSUE TITLE
StarMask 1.9.0 交易可能存在问题

### ISSUE THREAD

**Issue by jiangydev** [starcoinorg/starmask-extension#8]
## 问题
微信群和 Discord 上各有一人无法在[活动页](https://event.starcoin.org/)购买硬件钱包，交易状态为待处理，`链上无交易信息`；

## 版本
1.9.0

## 信息提供

操作的钱包地址：
https://stcscan.io/main/address/0xc71a528789eb29bc31e113eba568fbf4

交易截图：
![image](https://user-images.githubusercontent.com/25546833/128956613-2cdcb474-0d2c-448a-95c6-63cb0454bc87.png)

取消交易出现异常：
<img width="867" alt="f22f99b96062eba557ab2f60ce1c34f" src="https://user-images.githubusercontent.com/25546833/128956493-26b48268-c683-4a44-ad56-160d2aab2ae4.png">

**Comment by wk3368** [comment]
fixed in 1.9.1
