### ISSUE TITLE
bug: 执行 state.get_with_proof_by_root_raw 提示不存在

### ISSUE THREAD

**Issue by yubing744** [starcoinorg/starmask-extension#85]
通过 window.starcoin.request 执行 state.get_with_proof_by_root_raw 报错：

<img width="1750" alt="image" src="https://user-images.githubusercontent.com/1449069/193561375-c93c75cb-1604-4f5f-a2b3-1b36a2753a3d.png">

参数：
access_path: "0x574bc81805e18893aaecdae7e2c55f92/1/0x00000000000000000000000000000001::IdentifierNFT::IdentifierNFT<0x00000000000000000000000000000001::DAOSpace::DAOMember<0x4e375bb50d5b32a965b6e783e55a7cef::TESTDAO::TESTDAO>,0x00000000000000000000000000000001::DAOSpace::DAOMemberBody<0x4e375bb50d5b32a965b6e783e55a7cef::TESTDAO::TESTDAO>>"
state_root: "0x495d0430dc40cb608a2fff3e3b26e2b8e21510effe78a22eb6239d962753423e"

**Comment by jolestar** [comment]
> 通过 window.starcoin.request 执行 state.get_with_proof_by_root_raw 报错：
> 
> <img alt="image" width="1750" src="https://user-images.githubusercontent.com/1449069/193561375-c93c75cb-1604-4f5f-a2b3-1b36a2753a3d.png">
> 
> 参数： access_path: "0x574bc81805e18893aaecdae7e2c55f92/1/0x00000000000000000000000000000001::IdentifierNFT::IdentifierNFT<0x00000000000000000000000000000001::DAOSpace::DAOMember<0x4e375bb50d5b32a965b6e783e55a7cef::TESTDAO::TESTDAO>,0x00000000000000000000000000000001::DAOSpace::DAOMemberBody<0x4e375bb50d5b32a965b6e783e55a7cef::TESTDAO::TESTDAO>>" state_root: "0x495d0430dc40cb608a2fff3e3b26e2b8e21510effe78a22eb6239d962753423e"

是不是你本地的版本比较旧？

**Comment by yubing744** [comment]
我升级一下钱包试一下

**Comment by yubing744** [comment]
@jolestar 我试了升级到最新的钱包版本也不行，后来我分析了 starmask-extension 源码，发现他内部有权限控制，配置有一个透传的RPC方法白名单：

https://github.com/starcoinorg/starmask-extension/blob/6bdc25c7627b07ae02bc43793653cb01d1c370d9/app/scripts/controllers/permissions/enums.js#L36

**Comment by jolestar** [comment]
> @jolestar 我试了升级到最新的钱包版本也不行，后来我分析了 starmask-extension 源码，发现他内部有权限控制，配置有一个透传的RPC方法白名单：
> 
> https://github.com/starcoinorg/starmask-extension/blob/6bdc25c7627b07ae02bc43793653cb01d1c370d9/app/scripts/controllers/permissions/enums.js#L36-L114

@wk3368 这个白名单是不是没必要？是为了防止恶意请求？

**Comment by yubing744** [comment]
@jolestar 我尝试直接使用 starcoin.js 的 JsonRpcProvider 可以调用成功了。

**Comment by jolestar** [comment]
可以把 https://starcoinorg.github.io/jsonrpcdoc/#/ 中的 [Chain API](https://starcoinorg.github.io/jsonrpcdoc/#/chain)
[Contract API](https://starcoinorg.github.io/jsonrpcdoc/#/contract_api)
[State API](https://starcoinorg.github.io/jsonrpcdoc/#/state)
[Txpool API](https://starcoinorg.github.io/jsonrpcdoc/#/txpool)

四种接口全部加进去

**Comment by wk3368** [comment]
目前的window.starcoin发出的请求都是GET，这个是POST 所以不支持！

最好就是dapp自己用xios来自己发xhr请求。

**Comment by jolestar** [comment]
> 目前的window.starcoin发出的请求都是GET，这个是POST 所以不支持！
> 
> 最好就是dapp自己用xios来自己发xhr请求。
> 
> window.starcoin.chainId = '0xfb'
> 
> 可以根据下面的map 得到对应的rpcUrl，来发送任意GET/POST 请求
> 
> { providerType: 'main', rpcUrl: 'https://main-seed.starcoin.org', chainId: '0x1'} { providerType: 'barnard', rpcUrl: 'https://barnard-seed.starcoin.org', chainId: '0xfb'} { providerType: 'halley', rpcUrl: 'https://halley-seed.starcoin.org', chainId: '0xfd'} { providerType: 'proxima', rpcUrl: 'https://proxima-seed.starcoin.org', chainId: '0xfc'}

starcoin 的 RPC 都是 post 呀

**Comment by wk3368** [comment]
fixed in 4.8.0
