### ISSUE TITLE
[security] the wallet leak recovery phrase

### ISSUE THREAD

**Issue by maldiohead** [starcoinorg/starmask-extension#87]
details have send to the teams. for the senstive reason , will not plublic the details.

**Comment by wk3368** [comment]
Same issue in Metamask: https://github.com/MetaMask/metamask-extension/pull/14016

**Comment by wk3368** [comment]
before:
<img width="860" alt="image" src="https://user-images.githubusercontent.com/171268/200104216-afdcd3f0-578a-4372-b936-4b2052dbefd5.png">


after:
<img width="823" alt="image" src="https://user-images.githubusercontent.com/171268/200104173-0cb6ca74-7f4b-4834-8fe1-5c84ffcabf65.png">

**Comment by wk3368** [comment]
fixed in v5.1.0
